# server:
#   port: 8080

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port} 

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

spring:
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/v1/students/**
          # filters:
          #   - StripPrefix=3

        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**
          # filters:
          #   - StripPrefix=3

        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/v1/loans/**
          # filters:
          #   - StripPrefix=3

          # gateway yaml
        - id: student-service-docs
          uri: lb://student-service
          predicates:
            - Path=/aggregate/student-service/v3/api-docs
          filters:
            - RewritePath=/aggregate/student-service/(?<remaining>.*), /api/v1/students/$\{remaining}


        - id: book-service-docs
          uri: lb://book-service
          predicates:
            - Path=/aggregate/book-service/v3/api-docs
          filters:
            - RewritePath=/aggregate/book-service/(?<remaining>.*), /$\{remaining}

        - id: loan-service-docs
          uri: lb://loan-service
          predicates:
            - Path=/aggregate/loan-service/v3/api-docs
          filters:
            - RewritePath=/aggregate/loan-service/(?<remaining>.*), /$\{remaining}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: student-service
        url: /aggregate/student-service/v3/api-docs
      - name: book-service
        url: /aggregate/book-service/v3/api-docs
      - name: loan-service
        url: /aggregate/loan-service/v3/api-docs
