server:
  port: 8083
  servlet:
    context-path: /api/loans

spring:
  datasource:
    username: dhaval
    password: dhaval123
    url: jdbc:postgresql://localhost:5433/loandb

springdoc:
  packages-to-scan: com.lms.loan_service.controller
  paths-to-match: /**
