server:
  port: 8083
  servlet:
    context-path: /api/v1/loans

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/loandb
    username: ${LMS_DB_USER}
    password: ${LMS_DB_PASSWORD}

springdoc:
  packages-to-scan: com.lms.loan_service.controller
  paths-to-match: /**
